### ISSUE TITLE
Not able to run the project

### ISSUE THREAD

**Issue by shameemreza** [muhammadtalhasultan/Sirat-E-Mustaqeem#2]
Get build failed by running FLutter run:

`Xcode's output:
↳
    In file included from
    /Users/shameem/flutter/.pub-cache/hosted/pub.dartlang.org/geolocator_apple-1.0.0/ios/Classes/Handlers/LocationAccuracyHandler.m:10:
    /Users/shameem/flutter/.pub-cache/hosted/pub.dartlang.org/geolocator_apple-1.0.0/ios/Classes/Handlers/LocationAccuracyHandler.h:22:60:
    warning: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]
                                          purposeKey:(NSString *)purposeKey;
                                                               ^
    /Users/shameem/flutter/.pub-cache/hosted/pub.dartlang.org/geolocator_apple-1.0.0/ios/Classes/Handlers/LocationAccuracyHandler.h:22:60:
    note: insert '_Nullable' if the pointer may be null
                                          purposeKey:(NSString *)purposeKey;
                                                               ^
                                                                _Nullable
    /Users/shameem/flutter/.pub-cache/hosted/pub.dartlang.org/geolocator_apple-1.0.0/ios/Classes/Handlers/LocationAccuracyHandler.h:22:60:
    note: insert '_Nonnull' if the pointer should never be null
                                          purposeKey:(NSString *)purposeKey;
                                                               ^
                                                                _Nonnull
    1 warning generated.
    In file included from
    /Users/shameem/flutter/.pub-cache/hosted/pub.dartlang.org/geolocator_apple-1.0.0/ios/Classes/GeolocatorPlugin.m:11:
    /Users/shameem/flutter/.pub-cache/hosted/pub.dartlang.org/geolocator_apple-1.0.0/ios/Classes/Handlers/LocationAccuracyHandler.h:22:60:
    warning: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]
                                          purposeKey:(NSString *)purposeKey;
                                                               ^
    /Users/shameem/flutter/.pub-cache/hosted/pub.dartlang.org/geolocator_apple-1.0.0/ios/Classes/Handlers/LocationAccuracyHandler.h:22:60:
    note: insert '_Nullable' if the pointer may be null
                                          purposeKey:(NSString *)purposeKey;
                                                               ^
                                                                _Nullable
    /Users/shameem/flutter/.pub-cache/hosted/pub.dartlang.org/geolocator_apple-1.0.0/ios/Classes/Handlers/LocationAccuracyHandler.h:22:60:
    note: insert '_Nonnull' if the pointer should never be null
                                          purposeKey:(NSString *)purposeKey;
                                                               ^
                                                                _Nonnull
    1 warning generated.
    In file included from
    /Users/shameem/flutter/.pub-cache/hosted/pub.dartlang.org/geolocator_apple-1.0.0/ios/Classes/Handlers/LocationAccuracyHandler.m:10:
    /Users/shameem/flutter/.pub-cache/hosted/pub.dartlang.org/geolocator_apple-1.0.0/ios/Classes/Handlers/LocationAccuracyHandler.h:22:60:
    warning: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]
                                          purposeKey:(NSString *)purposeKey;
                                                               ^
    /Users/shameem/flutter/.pub-cache/hosted/pub.dartlang.org/geolocator_apple-1.0.0/ios/Classes/Handlers/LocationAccuracyHandler.h:22:60:
    note: insert '_Nullable' if the pointer may be null
                                          purposeKey:(NSString *)purposeKey;
                                                               ^
                                                                _Nullable
    /Users/shameem/flutter/.pub-cache/hosted/pub.dartlang.org/geolocator_apple-1.0.0/ios/Classes/Handlers/LocationAccuracyHandler.h:22:60:
    note: insert '_Nonnull' if the pointer should never be null
                                          purposeKey:(NSString *)purposeKey;
                                                               ^
                                                                _Nonnull
    1 warning generated.
    In file included from
    /Users/shameem/flutter/.pub-cache/hosted/pub.dartlang.org/geolocator_apple-1.0.0/ios/Classes/GeolocatorPlugin.m:11:
    /Users/shameem/flutter/.pub-cache/hosted/pub.dartlang.org/geolocator_apple-1.0.0/ios/Classes/Handlers/LocationAccuracyHandler.h:22:60:
    warning: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]
                                          purposeKey:(NSString *)purposeKey;
                                                               ^
    /Users/shameem/flutter/.pub-cache/hosted/pub.dartlang.org/geolocator_apple-1.0.0/ios/Classes/Handlers/LocationAccuracyHandler.h:22:60:
    note: insert '_Nullable' if the pointer may be null
                                          purposeKey:(NSString *)purposeKey;
                                                               ^
                                                                _Nullable
    /Users/shameem/flutter/.pub-cache/hosted/pub.dartlang.org/geolocator_apple-1.0.0/ios/Classes/Handlers/LocationAccuracyHandler.h:22:60:
    note: insert '_Nonnull' if the pointer should never be null
                                          purposeKey:(NSString *)purposeKey;
                                                               ^
                                                                _Nonnull
    1 warning generated.
    lib/src/core/util/controller/location_controller.dart:101:47: Error: Getter not found: 'REVERSE_GEOCODING_URL'.
          ApiService(networkClient: NetworkClient(REVERSE_GEOCODING_URL));
                                                  ^^^^^^^^^^^^^^^^^^^^^
    lib/src/core/util/controller/location_controller.dart:106:12: Error: Getter not found: 'GOOGLE_API_KEY'.
        'key': GOOGLE_API_KEY,
               ^^^^^^^^^^^^^^`

After reviewing what I found that some information is missing:

* Database giving 404 error: siratemustaqeem-db.db
* GOOGLE_API_KEY missing.

Can you let me know which google API you need? Map or location? Also, can you share the Database file?

**Comment by shameemreza** [comment]
Database issue I resolved, can you share about that API, please?

**Comment by CadbroomPr10** [comment]
@shameemreza 
I ran into the same problem, 
and here's a brief explanation;



```
Running Gradle task 'assembleDebug'...                          
lib/src/core/util/controller/location_controller.dart:101:47: Error: Getter not found: 'REVERSE_GEOCODING_URL'.
      ApiService(networkClient: NetworkClient(REVERSE_GEOCODING_URL));
                                              ^^^^^^^^^^^^^^^^^^^^^
lib/src/core/util/controller/location_controller.dart:106:12: Error: Getter not found: 'GOOGLE_API_KEY'.
    'key': GOOGLE_API_KEY,

FAILURE: Build failed with an exception.

* Where:
Script '/Users/builder/programs/flutter_2_5_3/packages/flutter_tools/gradle/flutter.gradle' line: 1005

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command '/Users/builder/programs/flutter_2_5_3/bin/flutter'' finished with non-zero exit value 1
```

**Comment by shameemreza** [comment]
You need to add your GOOGLE_API_KEY in constant and also the REVERSE_GEOCODING_URL. But I don't know where to get the REVERSE_GEOCODING_URL or how it will be.

**Comment by muhammadtalhasultan** [comment]
I have fixed the issues please check the updated project

**Comment by mroyyan** [comment]
build failed when flutter run, can you fix it?

```
Error: The argument type 'BlocBuilder<ThemeBloc, ThemeState> Function()' can't be assigned to the parameter type 'Widget Function(BuildContext, Widget?)'.
 - 'BlocBuilder' is from 'package:flutter_bloc/src/bloc_builder.dart' ('../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/flutter_bloc-7.3.3/lib/src/bloc_builder.dart').
 - 'ThemeBloc' is from 'package:sirat_e_mustaqeem/src/core/util/bloc/theme/theme_bloc.dart' ('lib/src/core/util/bloc/theme/theme_bloc.dart').
 - 'ThemeState' is from 'package:sirat_e_mustaqeem/src/core/util/bloc/theme/theme_bloc.dart' ('lib/src/core/util/bloc/theme/theme_bloc.dart').
 - 'Widget' is from 'package:flutter/src/widgets/framework.dart' ('/D:/flutter/packages/flutter/lib/src/widgets/framework.dart').
 - 'BuildContext' is from 'package:flutter/src/widgets/framework.dart' ('/D:/flutter/packages/flutter/lib/src/widgets/framework.dart').
                builder: () {
                         ^
lib/src/features/bottom_tab/screen/tab_screen.dart:26:20: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('/D:/flutter/packages/flutter/lib/src/widgets/binding.dart').
    WidgetsBinding.instance!.addObserver(this);
                   ^
lib/src/features/bottom_tab/screen/tab_screen.dart:32:20: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('/D:/flutter/packages/flutter/lib/src/widgets/binding.dart').
    WidgetsBinding.instance!.removeObserver(this);
                   ^
lib/src/features/quran/screen/option_screen.dart:107:38: Error: Required named parameter 'onChanged' must be provided.
                return DropdownButton(
                                     ^
/D:/flutter/packages/flutter/lib/src/material/dropdown.dart:853:3: Context: Found this candidate, but the arguments don't match.
  DropdownButton({
  ^^^^^^^^^^^^^^
lib/src/features/quran/screen/option_screen.dart:248:38: Error: Required named parameter 'onChanged' must be provided.
                return DropdownButton(
                                     ^
/D:/flutter/packages/flutter/lib/src/material/dropdown.dart:853:3: Context: Found this candidate, but the arguments don't match.
  DropdownButton({
  ^^^^^^^^^^^^^^
lib/src/features/quran/screen/option_screen.dart:358:38: Error: Required named parameter 'onChanged' must be provided.
                return DropdownButton(
                                     ^
/D:/flutter/packages/flutter/lib/src/material/dropdown.dart:853:3: Context: Found this candidate, but the arguments don't match.
  DropdownButton({
  ^^^^^^^^^^^^^^


FAILURE: Build failed with an exception.

* Where:
Script 'D:\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 1156

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'D:\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 19s
Exception: Gradle task assembleDebug failed with exit code 1
```

**Comment by shohelic** [comment]
Can anybody help me-----------

══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following StateError was thrown building _InheritedProviderScope<PercentBloc?>(value: <not yet
loaded>):
Bad state: add(DownloadDatabase) was called without a registered event handler.
Make sure to register a handler via on<DownloadDatabase>((event, emit) {...})

The relevant error-causing widget was:
  _InheritedProviderScope<PercentBloc?>
  _InheritedProviderScope:file:///C:/flutter/.pub-cache/hosted/pub.dartlang.org/provider-6.0.5/lib/src/inherited_provider.dart:161:12

**Comment by mjawad653** [comment]
I cloned this project and built apk but it shows blank screen

**Comment by uosgcedupk** [comment]
Hi, Dear i hope you are doing Well, Dear Sir This App still have bugs, when i run on my mobile or others devices , it will be crashes , I have Request to you that please Fixed All Issues , i shall be very thankful to you. your app is so better , Please solved the bugs.

**Comment by muhammadtalhasultan** [comment]
All Packages Updated, Please check the latest version of code

**Comment by Basicshitbruh** [comment]
Hey
This link doesnt work: https://talhasultan.dev/assets/siratemustaqeem-db.db

**Comment by uosgcedupk** [comment]
Dear Muhammadtalhasultan/Sirat-E-Mustaqeem
Application crashed after Complete  importing from github.
