### ISSUE TITLE
Getting Error in app when i run . Please Solved This Error/ Issus 

### ISSUE THREAD

**Issue by uniqekidz** [muhammadtalhasultan/Sirat-E-Mustaqeem#4]
Launching lib\main.dart on SM A715F in debug mode...
Running Gradle task 'assembleDebug'...
Warning: Mapping new ns http://schemas.android.com/repository/android/common/02 to old ns http://schemas.android.com/repository/android/common/01
Warning: Mapping new ns http://schemas.android.com/repository/android/generic/02 to old ns http://schemas.android.com/repository/android/generic/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/02 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/02 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/02 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01
/C:/flutter/.pub-cache/hosted/pub.dartlang.org/platform-3.0.0/lib/src/interface/local_platform.dart:46:19: Error: Member not found: 'packageRoot'.
      io.Platform.packageRoot; // ignore: deprecated_member_use
                  ^^^^^^^^^^^
lib/src/features/quran/screen/option_screen.dart:107:38: Error: Required named parameter 'onChanged' must be provided.
                return DropdownButton(
                                     ^
/C:/flutter/packages/flutter/lib/src/material/dropdown.dart:865:3: Context: Found this candidate, but the arguments don't match.
  DropdownButton({
  ^^^^^^^^^^^^^^
lib/src/features/quran/screen/option_screen.dart:248:38: Error: Required named parameter 'onChanged' must be provided.
                return DropdownButton(
                                     ^
/C:/flutter/packages/flutter/lib/src/material/dropdown.dart:865:3: Context: Found this candidate, but the arguments don't match.
  DropdownButton({
  ^^^^^^^^^^^^^^
lib/src/features/quran/screen/option_screen.dart:358:38: Error: Required named parameter 'onChanged' must be provided.
                return DropdownButton(
                                     ^
/C:/flutter/packages/flutter/lib/src/material/dropdown.dart:865:3: Context: Found this candidate, but the arguments don't match.
  DropdownButton({
  ^^^^^^^^^^^^^^

FAILURE: Build failed with an exception.

* Where:
Script 'C:\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 1102

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'C:\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 24s
Exception: Gradle task assembleDebug failed with exit code 1
---------------------------------------------------------------
if i removed Dropdown then issues is belows 

/C:/flutter/.pub-cache/hosted/pub.dartlang.org/platform-3.0.0/lib/src/interface/local_platform.dart:46:19: Error: Member not found: 'packageRoot'.
      io.Platform.packageRoot; // ignore: deprecated_member_use
                  ^^^^^^^^^^^

FAILURE: Build failed with an exception.

* Where:
Script 'C:\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 1102

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'C:\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 45s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by muhammadtalhasultan** [comment]
fix with latest verison
