### ISSUE TITLE
flutter run failed

### ISSUE THREAD

**Issue by feizezadeh** [muhammadtalhasultan/Sirat-E-Mustaqeem#5]
I wanted to run this project when I encountered this error after the flutter run command, please help me. 
Thanks

./../.pub-cache/hosted/pub.dartlang.org/flutter_screenutil-5.0.0+2/lib/screen_util.dart:42:33: Warning: Operand of null-aware operation '?.' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../flutter/packages/flutter/lib/src/widgets/binding.dart').
    var window = WidgetsBinding.instance?.window ?? ui.window;
                                ^
lib/src/features/bottom_tab/screen/tab_screen.dart:26:20: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../flutter/packages/flutter/lib/src/widgets/binding.dart').
    WidgetsBinding.instance!.addObserver(this);
                   ^
lib/src/features/bottom_tab/screen/tab_screen.dart:32:20: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../flutter/packages/flutter/lib/src/widgets/binding.dart').
    WidgetsBinding.instance!.removeObserver(this);
                   ^
../../.pub-cache/hosted/pub.dartlang.org/provider-5.0.0/lib/src/inherited_provider.dart:391:26: Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('../../flutter/packages/flutter/lib/src/scheduler/binding.dart').
        SchedulerBinding.instance!.addPostFrameCallback((_) {
                         ^
../../.pub-cache/hosted/pub.dartlang.org/platform-3.0.0/lib/src/interface/local_platform.dart:46:19: Error: Member not found: 'packageRoot'.
      io.Platform.packageRoot; // ignore: deprecated_member_use
                  ^^^^^^^^^^^
lib/src/features/quran/screen/option_screen.dart:107:38: Error: Required named parameter 'onChanged' must be provided.
                return DropdownButton(
                                     ^
../../flutter/packages/flutter/lib/src/material/dropdown.dart:853:3: Context: Found this candidate, but the arguments don't match.
  DropdownButton({
  ^^^^^^^^^^^^^^
lib/src/features/quran/screen/option_screen.dart:248:38: Error: Required named parameter 'onChanged' must be provided.
                return DropdownButton(
                                     ^
../../flutter/packages/flutter/lib/src/material/dropdown.dart:853:3: Context: Found this candidate, but the arguments don't match.
  DropdownButton({
  ^^^^^^^^^^^^^^
lib/src/features/quran/screen/option_screen.dart:358:38: Error: Required named parameter 'onChanged' must be provided.
                return DropdownButton(
                                     ^
../../flutter/packages/flutter/lib/src/material/dropdown.dart:853:3: Context: Found this candidate, but the arguments don't match.
  DropdownButton({
  ^^^^^^^^^^^^^^

FAILURE: Build failed with an exception.

* Where:
Script '/home/mehdi/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 1156

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command '/home/mehdi/flutter/bin/flutter'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 33m 56s
Running Gradle task 'assembleDebug'...                           2037.4s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by muhammadtalhasultan** [comment]
Fixed with new latest verison.
