### ISSUE TITLE
StateError (Bad state: add(DownloadDatabase) was called without a registered event handler. Make sure to register a handler via on<DownloadDatabase>((event, emit) {...}))

### ISSUE THREAD

**Issue by kjanwiri** [muhammadtalhasultan/Sirat-E-Mustaqeem#8]
Hi I'am getting the below error and unable to run the application.

StateError (Bad state: add(DownloadDatabase) was called without a registered event handler.
Make sure to register a handler via on<DownloadDatabase>((event, emit) {...}))

<img width="915" alt="Screenshot 2023-01-14 082126" src="https://user-images.githubusercontent.com/33275704/212450428-d1c0f59d-395d-40c1-9aaf-177f85519a34.png">

**Comment by ALLY-MAFTAH** [comment]
I'm also getting the same error

**Comment by berkeenes** [comment]
Use `flutter_bloc: ^7.2.0` and `hydrated_bloc: ^7.1.0` versions.

**Comment by muhammadtalhasultan** [comment]
All Packages Updated, Please check the latest version of code
